security:
    encoders:
        Percas\Entity\System\User:
            algorithm: auto
    providers:
        percas_user_provider:
            id: Percas\Core\Security\Provider\UserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            json_login:
                check_path: percas_security_login
            logout:
                path: percas_security_logout
                success_handler: Percas\Core\Security\Handler\LogoutSuccessHandler
#    access_control:
#        - { path: ^, roles: IS_AUTHENTICATED_FULLY }
