controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

system:
    resource: ../../src/Controller/System
    type: annotation
    prefix: /system
